/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData scan = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_330 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_group_3 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seminar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_contact = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid_kit = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_28 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_329 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
